### ISSUE TITLE
Training script of vtab-cifar100 under full fine-tuning

### ISSUE THREAD

**Issue by weeknan** [dongzelian/SSF#8]
Hi! 
I found it's hard to reproduce the cifar100 full fine-tuning results in Table 4 (68.9).
My bast reproduce result is using supervised pretrained vit-b, with lr=0.01, wd=1e-4 and sgd optimizer, and i got 66.3 top acc@1, which has a pretty large gap compared to 68.9. 
Could you provide the training script of vtab-cifar100 under full fine-tuning setting? 
Thanks!

**Comment by dongzelian** [comment]
@weeknan We do not actually run vtab-cifar100 full fine-tuning due to the resource limitation. Following VPT (https://arxiv.org/pdf/2203.12119.pdf) Table 13, you can find the vtab-cifar100 full fine-tuning results. Refer to VPT code (https://github.com/KMnP/vpt) for the specific implementation. Thanks!

**Comment by weeknan** [comment]
ok，thanks！
